nome = input('Qual o seu nome?')
idade = input('Qual a sua idade?')
peso = input('Qual o seu peso?')
print("O seu nome é:" + nome)
print("Você tem:"  +  idade, "anos")
print("E tem:"  +  peso, "quilos" )
